language: php

php:
  - 5.3

env:
  global:
    # The user you interact with Pantheon as
    - PEMAIL='kevin@bt48.com'

    # SECRET/PRIVATE VARIABLES
    #
    # These are created by using the travis command locally to encrypt some values.
    #
    # See: http://docs.travis-ci.com/user/build-configuration/#Secure-environment-variables
    #
    # PEMAIL environment variable: represents the Pantheon account e-mail with
    # access to this site. Used to authenticate to Pantheon via Terminus. You
    # must cd to your project root and run:
    #
    # travis encrypt PEMAIL='test@example.com'
    #


    #
    # PPASS environment variable: represents the Pantheon account password for
    # the above encrypted e-mail address. Run:
    #
    # travis encrypt PPASS='my_account_password'
    #


before_install:
    # Place a passphrase-free ssh key so that you can clone and push to your
    # Pantheon git repository.
    #
    # Use the travis encrypt-file command to generate your own.
    #
    # See: http://docs.travis-ci.com/user/encrypting-files/
    #



install:
    - echo "StrictHostKeyChecking no" > ~/.ssh/config

    # Install Drush and Behat
    - composer install

    - sh -e /etc/init.d/xvfb start
    - export DISPLAY=:99.0
    - wget http://selenium.googlecode.com/files/selenium-server-standalone-2.31.0.jar
    - java -jar selenium-server-standalone-2.31.0.jar > /dev/null &
    - sleep 5	

before_script:


script:

    # Generate a random branch / multidev name, prefixed with "ci" followed
    # by the Travis build number. Note, due to Pantheon multidev environment
    # name limits, builds will start failing at #100000.


    # You can use $PHOST as a reference to the resulting multidev hostname.
    - BEHAT_BASE_URL="extensions[Behat\MinkExtension\Extension][base_url]=http://dev-travis-test.pantheon.io"
    - echo $BEHAT_BASE_URL
    - export BEHAT_PARAMS=$BEHAT_BASE_URL
    - bash scripts/run_tests.sh
    
after_script:
  # General-purpose clean-up could go here.


after_success:
  # Maybe promote to test here?

after_failure:
  # Maybe roll back?

notifications:
  email:
    recipients:
      # - kevin@bt48.com
    on_success: always
    on_failure: always
